In [21]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets, neighbors

iris = datasets.load_iris()
# print(iris)
iris_x = iris.data
iris_y = iris.target
print ("Number point data :",len(iris_y))
print('Number of classes :',len(np.unique(iris_y)))

X0 = iris_x[iris_y == 0,:]
print("Sample of class 0 :", X0[:5,:])
X1 = iris_x[iris_y == 1,:]
print("Sample of class 1 :", X1[:5,:])
X2 = iris_x[iris_y == 2,:]
print("Sample of class 2 :", X0[:5,:])

Number point data : 150
Number of classes : 3
Sample of class 0 : [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
Sample of class 1 : [[7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]]
Sample of class 2 : [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [88]:
# train set, test set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(iris_x, iris_y, test_size =0.2)
print('len of train :', len(x_train))
print('len of test :', len(x_test))

clf = neighbors.KNeighborsClassifier(n_neighbors =10 , p =2, weights ='distance') #p =2 : chuan norm 2, weights : trong so (khoang cach can gan => trong so can lon)
print(clf)
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)
print("Ground truth: ", y_test[20:40])
print("Predict: ", y_pred[20:40])
from sklearn.metrics import accuracy_score
print("Accuracy score: ",100* accuracy_score(y_test, y_pred))

len of train : 120
len of test : 30
KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=10, p=2,
           weights='distance')
Ground truth:  [1 1 2 1 2 1 1 2 0 2]
Predict:  [1 1 2 1 2 1 1 2 0 2]
Accuracy score:  100.0


In [166]:
# ngoài 2 trọng số weight: uniform, distance => tự tạo ra trọng số bằng hàm
def myweight(distance):
    sigma =0.5 # we can change this number
    return np.exp(-distance**2/sigma)
# train set, test set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(iris_x, iris_y, test_size =0.2)
print('len of train :', len(x_train))
print('len of test :', len(x_test))

clf = neighbors.KNeighborsClassifier(n_neighbors =10 , p =2, weights =myweight) #p =2 : chuan norm 2, weights : trong so (khoang cach can gan => trong so can lon)
print(clf)
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)
print("Ground truth: ", y_test[20:40])
print("Predict: ", y_pred[20:40])
from sklearn.metrics import accuracy_score
print("Accuracy score: ",100* accuracy_score(y_test, y_pred))

len of train : 120
len of test : 30
KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=10, p=2,
           weights=<function myweight at 0x000001C8F20FCE18>)
Ground truth:  [1 2 0 0 0 0 2 1 2 1]
Predict:  [1 2 0 0 0 0 2 1 2 1]
Accuracy score:  100.0
